import type {Profile} from "@/features/profiles/types";
const DB_NAME="nuipita";const DB_VERSION=2;const STORES=["profiles","garmentDrafts","pouchDrafts","results","settings"] as const;export type StoreName=typeof STORES[number];export const STORE_LIMITS:Record<StoreName,number>={profiles:30,garmentDrafts:10,pouchDrafts:10,results:20,settings:20};
function migrate(db:IDBDatabase,transaction:IDBTransaction,oldVersion:number){if(oldVersion<1){for(const name of STORES)if(!db.objectStoreNames.contains(name))db.createObjectStore(name,{keyPath:"id"})}if(oldVersion<2){for(const name of STORES){const store=transaction.objectStore(name);if(!store.indexNames.contains("updatedAt"))store.createIndex("updatedAt","updatedAt",{unique:false})}}}
let memoryOnly=false;const memoryStores=new Map<StoreName,Map<string,unknown>>(STORES.map(store=>[store,new Map<string,unknown>()]));export function storageUnavailable(){return memoryOnly||typeof indexedDB==="undefined"}
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{if(typeof indexedDB==="undefined"){reject(new Error("unavailable"));return}const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=event=>migrate(req.result,req.transaction!,event.oldVersion);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error??new Error("open"))})}
async function request<T>(store:StoreName,mode:IDBTransactionMode,action:(os:IDBObjectStore)=>IDBRequest<T>|void){if(memoryOnly)return undefined;let db:IDBDatabase;try{db=await openDb()}catch{memoryOnly=true;return undefined}return new Promise<T|undefined>((resolve,reject)=>{const tx=db.transaction(store,mode);const result=action(tx.objectStore(store));if(!result){tx.oncomplete=()=>{db.close();resolve(undefined)};tx.onerror=()=>{db.close();reject(tx.error)};return}result.onsuccess=()=>{db.close();resolve(result.result)};result.onerror=()=>{db.close();reject(result.error)}})}
export async function listRecords<T=Record<string,unknown>>(store:StoreName){if(memoryOnly)return [...memoryStores.get(store)!.values()] as T[];return (await request<T[]>(store,"readonly",os=>os.getAll()))??[...memoryStores.get(store)!.values()] as T[]}
export async function putRecord<T extends {id:string;createdAt?:string;updatedAt?:string}>(store:StoreName,value:T){const records=await listRecords<T>(store);if(memoryOnly){memoryStores.get(store)!.set(value.id,value);if(store!=="profiles"&&records.every(record=>record.id!==value.id)&&records.length+1>STORE_LIMITS[store]){const next=[...records,value].sort((a,b)=>(a.updatedAt??a.createdAt??"").localeCompare(b.updatedAt??b.createdAt??""));for(const old of next.slice(0,Math.max(0,next.length-STORE_LIMITS[store])))memoryStores.get(store)!.delete(old.id)}return}await request(store,"readwrite",os=>os.put(value));if(store!=="profiles"&&records.every(record=>record.id!==value.id)&&records.length+1>STORE_LIMITS[store]){const next=[...records,value].sort((a,b)=>(a.updatedAt??a.createdAt??"").localeCompare(b.updatedAt??b.createdAt??""));for(const old of next.slice(0,Math.max(0,next.length-STORE_LIMITS[store])))await request(store,"readwrite",os=>os.delete(old.id))}}
export async function clearStore(store:StoreName){if(memoryOnly){memoryStores.get(store)!.clear();return}await request(store,"readwrite",os=>{os.clear()})}
export async function listProfiles(){return listRecords<Profile>("profiles")}
export async function putProfile(profile:Profile){const profiles=await listProfiles();const values=Object.values(profile.measurements);if(!profile.name.trim()||profile.name.length>40||values.some(value=>value!==undefined&&(!Number.isFinite(value)||value<.1||value>200)))throw new Error("invalid-profile");if(!profiles.some(x=>x.id===profile.id)&&profiles.length>=STORE_LIMITS.profiles)throw new Error("profile-limit");if(memoryOnly)memoryStores.get("profiles")!.set(profile.id,profile);else await request("profiles","readwrite",os=>os.put(profile))}
export async function deleteProfile(id:string){if(memoryOnly)memoryStores.get("profiles")!.delete(id);else await request("profiles","readwrite",os=>os.delete(id))}
export function makeProfile(name:string):Profile{const now=new Date().toISOString();return {id:crypto.randomUUID(),name:name.trim().slice(0,40),shape:"round",softness:"balanced",avatarTheme:"coral",measurements:{},createdAt:now,updatedAt:now,dataVersion:1}}
export type Backup={version:1;profiles:Profile[];garmentDrafts:StoredRecord[];pouchDrafts:StoredRecord[];results:StoredRecord[];settings:StoredRecord[];exportedAt:string};
type StoredRecord={id:string;createdAt?:string;updatedAt?:string;[key:string]:unknown};
function validRecord(value:unknown):value is StoredRecord{return !!value&&typeof value==="object"&&typeof (value as {id?:unknown}).id==="string"&&String((value as {id:string}).id).length<=100}
export function validateBackup(value:unknown):value is Backup{if(!value||typeof value!=="object")return false;const x=value as Partial<Backup>;const validProfiles=Array.isArray(x.profiles)&&x.profiles.length<=30&&x.profiles.every(p=>{if(!p||typeof p!=="object")return false;const q=p as Profile;return typeof q.id==="string"&&q.id.length<=100&&typeof q.name==="string"&&q.name.length<=40&&q.dataVersion===1&&!!q.measurements&&Object.values(q.measurements).every(v=>v===undefined||(typeof v==="number"&&Number.isFinite(v)&&v>=.1&&v<=200))});return x.version===1&&validProfiles&&Array.isArray(x.garmentDrafts)&&x.garmentDrafts.length<=10&&x.garmentDrafts.every(validRecord)&&Array.isArray(x.pouchDrafts)&&x.pouchDrafts.length<=10&&x.pouchDrafts.every(validRecord)&&Array.isArray(x.results)&&x.results.length<=20&&x.results.every(validRecord)&&Array.isArray(x.settings)&&x.settings.length<=20&&x.settings.every(validRecord)}
export async function exportBackup():Promise<Backup>{return {version:1,profiles:await listProfiles(),garmentDrafts:await listRecords("garmentDrafts"),pouchDrafts:await listRecords("pouchDrafts"),results:await listRecords("results"),settings:await listRecords("settings"),exportedAt:new Date().toISOString()}}
export async function importBackup(value:unknown){if(!validateBackup(value))throw new Error("invalid-backup");for(const profile of value.profiles)await putProfile(profile);for(const [store,records] of [["garmentDrafts",value.garmentDrafts],["pouchDrafts",value.pouchDrafts],["results",value.results],["settings",value.settings]] as const)for(const record of records)await putRecord(store,record)}
export async function clearAllData(){for(const store of STORES)await clearStore(store)}
