"use client";
import {useState} from "react";
import {shareCardSvg,svgToPng} from "@/lib/share-card";

export function ShareActions({title,status,url}:{title:string;status:string;url:string}){
  const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);
  async function shareLink(){if(!url)return;try{const browserNavigator=navigator as Navigator & {share?:(data:ShareData)=>Promise<void>};if(browserNavigator.share)await browserNavigator.share({url,text:`${title}：${status}\n#ぬい活 #ぬいぴた`});else await navigator.clipboard?.writeText(url)}catch{/* user closed the native sheet */}}
  async function makeBlob(){return svgToPng(shareCardSvg(title,status))}
  async function saveImage(){setBusy(true);try{const blob=await makeBlob();const objectUrl=URL.createObjectURL(blob);const link=document.createElement("a");link.href=objectUrl;link.download="nuipita-share.png";link.click();URL.revokeObjectURL(objectUrl)}catch{await shareLink()}finally{setBusy(false)}}
  async function shareImage(){setBusy(true);try{const blob=await makeBlob();const file=new File([blob],"nuipita-share.png",{type:"image/png"});const browserNavigator=navigator as Navigator & {share?:(data:ShareData)=>Promise<void>;canShare?:(data:ShareData)=>boolean};if(browserNavigator.share&&browserNavigator.canShare?.({files:[file]}))await browserNavigator.share({files:[file],url,text:`${title}：${status}\n#ぬい活 #ぬいぴた`});else await saveImage()}catch{await shareLink()}finally{setBusy(false)}}
  const text=encodeURIComponent(`${title}：${status}\n#ぬい活 #ぬいぴた`);const encodedUrl=encodeURIComponent(url);
  return <><button className="secondary" onClick={()=>setOpen(true)}>共有</button>{open&&<div className="drawer" role="presentation" onClick={()=>setOpen(false)}><aside role="dialog" aria-modal="true" aria-label="共有" onClick={event=>event.stopPropagation()}><h2>共有</h2><div className="card stitch"><strong>{title}</strong><p className="small">{status}</p><span className="pill">ぬいぴた</span></div><p className="small">共有リンクを知っている人が見られます。</p><div className="actions"><button onClick={shareLink}>リンクを共有</button><button className="secondary" onClick={()=>navigator.clipboard?.writeText(url)}>リンクをコピー</button><button className="secondary" disabled={busy} onClick={shareImage}>{busy?"画像を用意中":"画像を共有"}</button><button className="secondary" disabled={busy} onClick={saveImage}>画像を保存</button><a className="button secondary" href={`https://twitter.com/intent/tweet?text=${text}&url=${encodedUrl}`} target="_blank" rel="noreferrer">Xで共有</a><a className="button secondary" href={`https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}`} target="_blank" rel="noreferrer">Facebookで共有</a><button className="secondary" onClick={()=>setOpen(false)}>閉じる</button></div></aside></div>}</>
}
