"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {GarmentChooser} from "@/components/fit/GarmentChooser";
import {ShareActions} from "@/components/share/ShareActions";
import {Toast} from "@/components/ui/Toast";
import {LoadingSkeleton} from "@/components/ui/LoadingSkeleton";
import {garmentFieldLabels,garmentRegistry,type GarmentField,type GarmentType} from "@/features/fit/garment-registry";
import {judgeFit,type FitPart,type PartStatus,type Stretch} from "@/features/fit/engine";
import {decodeShare,encodeShare} from "@/lib/share";
import {listProfiles,putRecord,storageUnavailable} from "@/lib/storage";
import type {Profile} from "@/features/profiles/types";

const statusLabels:Record<PartStatus|string,string>={blocked:"通らないかも",tight:"きつめかも",fit:"ぴったり寄り",roomy:"ゆったり寄り",short:"短めかも",long:"長めかも",unknown:"あと少し"};
const reasonLabels:Record<string,string>={HEAD_OPENING_TOO_SMALL:"開口が小さめです",HEAD_OPENING_TIGHT:"開口に余裕が少なめです",HEAD_ROOMY:"開口に余裕があります",BODY_TIGHT:"胴まわりに余裕が少なめです",BODY_ROOMY:"胴まわりに余裕があります",LENGTH_SHORT:"丈が短めです",LENGTH_LONG:"丈が長めです",MISSING_HEAD:"頭の採寸が必要です",MISSING_BODY:"胴まわりの採寸が必要です",MISSING_LENGTH:"丈の採寸が必要です",MISSING_COMPARISON:"比較する採寸が必要です"};
const stretchLabels:Record<Stretch,string>={none:"伸びない",low:"少し伸びる",medium:"ほどよく伸びる",high:"よく伸びる"};
const circumference=(field:GarmentField)=>field.toLowerCase().includes("circumference");

export default function FitPage(){
  const [garmentType,setGarmentType]=useState<GarmentType>("pullover");
  const [profiles,setProfiles]=useState<Profile[]>([]);const [selected,setSelected]=useState("");const [values,setValues]=useState<Record<string,string>>({});
  const [modes,setModes]=useState<Partial<Record<GarmentField,"circumference"|"flat">>>({});const [stretch,setStretch]=useState<Stretch>("medium");const [result,setResult]=useState<ReturnType<typeof judgeFit>|null>(null);const [notice,setNotice]=useState("");const [loaded,setLoaded]=useState(false);
  useEffect(()=>{const timer=window.setTimeout(()=>{if(storageUnavailable())setNotice("この端末では保存できません。今だけ使えます");const payload=new URLSearchParams(window.location.search).get("garment");const value=payload&&decodeShare(payload);if(value&&typeof value==="object"&&"garmentType" in value){const data=value as {garmentType?:GarmentType;measurements?:Record<string,number>};if(data.garmentType&&data.garmentType in garmentRegistry)setGarmentType(data.garmentType);if(data.measurements)setValues(Object.fromEntries(Object.entries(data.measurements).map(([key,number])=>[key,String(number)]))) }},0);listProfiles().then(value=>{setProfiles(value);setLoaded(true)}).catch(()=>{setLoaded(true);setNotice("この端末では保存できません。今だけ使えます")});return()=>window.clearTimeout(timer)},[]);
  const profile=profiles.find(item=>item.id===selected);const fields=garmentRegistry[garmentType].fields;
  function selectProfile(id:string){setSelected(id);const next=profiles.find(item=>item.id===id);if(next)setValues(current=>({...current,...Object.fromEntries(fields.map(field=>{const key=({openingCircumference:"headCircumference",neckCircumference:"neckCircumference",chestCircumference:"bodyCircumference",waistCircumference:"bodyCircumference",hipCircumference:"hipCircumference",bodyLength:"torsoLength",sleeveLength:"armLength",legLength:"legLength",headwearCircumference:"headCircumference",crownHeight:"headHeight"} as Record<GarmentField,keyof Profile["measurements"]>)[field];return [field,key?next.measurements[key]?.toString()??current[field]:current[field]]}))}))}
  function judge(){const garment=Object.fromEntries(fields.map(field=>{const number=Number(values[field]);return [field,Number.isFinite(number)&&number>=.1&&number<=200?number:undefined]})) as Partial<Record<GarmentField,number>>;const next=judgeFit({garmentType,garment,modes,plush:profile?.measurements??{},stretch,softness:profile?.softness??"balanced"});setResult(next);setNotice("")}
  async function saveResult(){if(!result)return;await putRecord("results",{id:crypto.randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),dataVersion:1,garmentType,profileId:selected,result});setNotice("判定を保存しました")}
  const sharePayload=result?encodeShare({kind:"fit",name:profile?.name,garmentType,overall:result.overall,score:result.score,parts:result.parts.map(part=>({field:part.field,status:part.status})),avatarTheme:profile?.avatarTheme}):"";
  const garmentPayload=encodeShare({kind:"garment",name:"ぬい服サイズ",garmentType,measurements:Object.fromEntries(fields.map(field=>[field,Number(values[field])]).filter(([,value])=>Number.isFinite(value))) });
  return <><h1 className="sr-only">ぬい服フィットチェッカー</h1><section className="hero"><span className="pill">ぬい服</span><h2>ぴったりを探す</h2><p className="small">{loaded&&profiles.length===0?"先にカルテを1枚作ると、うちのぬいの寸法で比べられます。":"服の寸法と、うちのぬいの寸法を比べます。"}</p></section>{!loaded&&<LoadingSkeleton label="カルテを読み込み中"/>}
    {loaded&&profiles.length===0&&<div className="card onboarding"><strong>服を選ぶ前に、カルテを作りましょう</strong><p className="small">登録は1体ずつ。全高・頭・胴・胴丈が分かれば始められます。</p><Link href="/nui"><button>カルテを作る</button></Link></div>}
    <GarmentChooser selected={garmentType} onChange={type=>{setGarmentType(type);setResult(null);setValues({})}}/>
    <div className="card stitch"><label className="field">うちのぬい<select aria-label="うちのぬい" value={selected} onChange={e=>selectProfile(e.target.value)}><option value="">{profiles.length?"選ぶ":"まだ登録されていません"}</option>{profiles.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{!profile&&<p className="small">{profiles.length?"カルテを選ぶと、登録済みの採寸値が入ります。":"先にカルテを作ると、ここで選べるようになります。"}</p>}<h2>{garmentRegistry[garmentType].label}の寸法</h2><p className="field-note">服の寸法を、販売ページやタグを見ながら入力します。</p><div className="grid">{fields.map(field=><label className="field" key={field}><span>{garmentFieldLabels[field]}</span><input inputMode="decimal" placeholder="cm" value={values[field]??""} onChange={e=>setValues(current=>({...current,[field]:e.target.value}))}/>{circumference(field)&&<select aria-label={`${garmentFieldLabels[field]}の測り方`} value={modes[field]??"circumference"} onChange={e=>setModes(current=>({...current,[field]:e.target.value as "circumference"|"flat"}))}><option value="circumference">一周</option><option value="flat">平置き</option></select>}</label>)}</div><label className="field">生地の伸びやすさ<select value={stretch} onChange={e=>setStretch(e.target.value as Stretch)}>{Object.entries(stretchLabels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><button onClick={judge}>判定する</button></div>
    {result&&<div className="card stitch"><span className="pill">{statusLabels[result.overall]}</span><h2>ぴた度 {result.overall==="unknown"?"—":result.score}</h2><p>判定確度：{({high:"しっかり",medium:"まずまず",low:"ざっくり"} as const)[result.confidence]}</p><div className="grid">{result.parts.map((part:FitPart)=><div className="card" key={part.field??part.name}><strong>{part.name}</strong><br/><span className="small">{statusLabels[part.status]}</span>{part.reasonCode&&<details><summary>理由を見る</summary><p className="small">{reasonLabels[part.reasonCode]??"採寸条件を確認してください"}</p></details>}</div>)}</div><p className="small">ぴた度は精密な物理測定ではなく、寸法比較の目安です。</p><div className="actions"><button onClick={saveResult}>保存</button><ShareActions title="ぬい服フィット" status={statusLabels[result.overall]} url={`${location.origin}/s/${sharePayload}`}/><button className="secondary" onClick={()=>navigator.clipboard?.writeText(`${location.origin}/s/${sharePayload}`)}>リンクをコピー</button><a href={`/g/${garmentPayload}`}><button className="secondary">服サイズリンク作成</button></a></div></div>}<Toast key={notice} message={notice}/><p className="small">判定は素材や形によって変わる、寸法から見た目安です。</p></>;
}
