"use client";
import Image from "next/image";
import Link from "next/link";
import {useEffect,useState} from "react";
import {GarmentChooser} from "@/components/fit/GarmentChooser";
import {ShareActions} from "@/components/share/ShareActions";
import {Toast} from "@/components/ui/Toast";
import {LoadingSkeleton} from "@/components/ui/LoadingSkeleton";
import {garmentFieldLabels,garmentRegistry,type GarmentField,type GarmentType} from "@/features/fit/garment-registry";
import {judgeFit,type FitPart,type PartStatus,type Stretch} from "@/features/fit/engine";
import {decodeShare,encodeShare} from "@/lib/share";
import {listProfiles,listRecords,putRecord,storageUnavailable} from "@/lib/storage";
import type {Profile} from "@/features/profiles/types";

const statusLabels:Record<PartStatus|string,string>={blocked:"通らないかも",tight:"きつめかも",fit:"ぴったり寄り",roomy:"ゆったり寄り",short:"短めかも",long:"長めかも",unknown:"あと少し"};
const reasonLabels:Record<string,string>={HEAD_OPENING_TOO_SMALL:"開口が小さめです",HEAD_OPENING_TIGHT:"開口に余裕が少なめです",HEAD_ROOMY:"開口に余裕があります",BODY_TIGHT:"胴まわりに余裕が少なめです",BODY_ROOMY:"胴まわりに余裕があります",LENGTH_SHORT:"丈が短めです",LENGTH_LONG:"丈が長めです",MISSING_HEAD:"頭の採寸が必要です",MISSING_BODY:"胴まわりの採寸が必要です",MISSING_LENGTH:"丈の採寸が必要です",MISSING_COMPARISON:"比較する採寸が必要です"};
const stretchLabels:Record<Stretch,string>={none:"伸びない",low:"少し伸びる",medium:"ほどよく伸びる",high:"よく伸びる"};
const circumference=(field:GarmentField)=>field.toLowerCase().includes("circumference");
type SavedFit={id:string;createdAt?:string;updatedAt?:string;dataVersion:number;garmentType:GarmentType;profileId:string;garment:Partial<Record<GarmentField,number>>;modes:Partial<Record<GarmentField,"circumference"|"flat">>;stretch:Stretch;result:ReturnType<typeof judgeFit>};

export default function FitPage(){
  const [garmentType,setGarmentType]=useState<GarmentType>("pullover");
  const [profiles,setProfiles]=useState<Profile[]>([]);const [selected,setSelected]=useState("");const [values,setValues]=useState<Record<string,string>>({});const [savedResults,setSavedResults]=useState<SavedFit[]>([]);
  const [modes,setModes]=useState<Partial<Record<GarmentField,"circumference"|"flat">>>({});const [stretch,setStretch]=useState<Stretch>("medium");const [result,setResult]=useState<ReturnType<typeof judgeFit>|null>(null);const [notice,setNotice]=useState("");const [loaded,setLoaded]=useState(false);
  useEffect(()=>{const timer=window.setTimeout(()=>{if(storageUnavailable())setNotice("この端末では保存できません。今だけ使えます");const payload=new URLSearchParams(window.location.search).get("garment");const value=payload&&decodeShare(payload);if(value&&typeof value==="object"&&"garmentType" in value){const data=value as {garmentType?:GarmentType;measurements?:Record<string,number>};if(data.garmentType&&data.garmentType in garmentRegistry)setGarmentType(data.garmentType);if(data.measurements)setValues(Object.fromEntries(Object.entries(data.measurements).map(([key,number])=>[key,String(number)]))) }},0);listProfiles().then(value=>{setProfiles(value);setLoaded(true)}).catch(()=>{setLoaded(true);setNotice("この端末では保存できません。今だけ使えます")});listRecords<SavedFit>("results").then(records=>{const ordered=records.sort((a,b)=>(b.updatedAt??b.createdAt??"").localeCompare(a.updatedAt??a.createdAt??""));setSavedResults(ordered.slice(0,5));const savedId=new URLSearchParams(window.location.search).get("saved");const saved=ordered.find(record=>record.id===savedId);if(saved){setGarmentType(saved.garmentType);setSelected(saved.profileId);setValues(Object.fromEntries(Object.entries(saved.garment).map(([key,value])=>[key,String(value)])));setModes(saved.modes);setStretch(saved.stretch);setResult(saved.result)}}).catch(()=>{});return()=>window.clearTimeout(timer)},[]);
  const profile=profiles.find(item=>item.id===selected);const fields=garmentRegistry[garmentType].fields;const missingFitFields=!profile?["あなたのぬい"]:fields.filter(field=>{const value=Number(values[field]);return !Number.isFinite(value)||value<=0}).map(field=>garmentFieldLabels[field]);const canJudge=missingFitFields.length===0;
  function selectProfile(id:string){setSelected(id);const next=profiles.find(item=>item.id===id);if(next)setValues(current=>({...current,...Object.fromEntries(fields.map(field=>{const key=({openingCircumference:"headCircumference",neckCircumference:"neckCircumference",chestCircumference:"bodyCircumference",waistCircumference:"bodyCircumference",hipCircumference:"hipCircumference",bodyLength:"torsoLength",sleeveLength:"armLength",legLength:"legLength",headwearCircumference:"headCircumference",crownHeight:"headHeight"} as Record<GarmentField,keyof Profile["measurements"]>)[field];return [field,key?next.measurements[key]?.toString()??current[field]:current[field]]}))}))}
  function judge(){const garment=Object.fromEntries(fields.map(field=>{const number=Number(values[field]);return [field,Number.isFinite(number)&&number>=.1&&number<=200?number:undefined]})) as Partial<Record<GarmentField,number>>;const next=judgeFit({garmentType,garment,modes,plush:profile?.measurements??{},stretch,softness:profile?.softness??"balanced"});setResult(next);setNotice("")}
  async function saveResult(){if(!result||!profile)return;const garment=Object.fromEntries(fields.map(field=>[field,Number(values[field])]).filter(([,value])=>Number.isFinite(value))) as Partial<Record<GarmentField,number>>;const record={id:crypto.randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),dataVersion:1,garmentType,profileId:selected,garment,modes,stretch,result} satisfies SavedFit;await putRecord("results",record);setSavedResults(current=>[record,...current.filter(item=>item.id!==record.id)].slice(0,5));setNotice("判定を保存しました")}
  const sharePayload=result?encodeShare({kind:"fit",name:profile?.name,garmentType,overall:result.overall,score:result.score,parts:result.parts.map(part=>({field:part.field,status:part.status})),avatarTheme:profile?.avatarTheme}):"";
  const garmentPayload=encodeShare({kind:"garment",name:"ぬい服サイズ",garmentType,measurements:Object.fromEntries(fields.map(field=>[field,Number(values[field])]).filter(([,value])=>Number.isFinite(value))) });
  return <><h1 className="sr-only">ぬい服フィットチェッカー</h1><section className="hero fit-hero"><div className="hero-favicon"><Image src="/favicon-v3.png" alt="ぬいぴた" width={92} height={92} priority/></div><p className="hero-message">ぬいを登録すると、どの服がぴったりなのか見える化します</p></section>{!loaded&&<LoadingSkeleton label="登録したぬいを読み込み中"/>}
    {loaded&&profiles.length===0&&<div className="card onboarding"><strong>服を選ぶ前に、あなたのぬいを登録しましょう</strong><p className="small">登録は1体ずつ。全高・頭・胴・胴丈が分かれば始められます。</p><Link href="/nui"><button>ぬいを登録する</button></Link></div>}
    {savedResults.length>0&&<section className="card recent-results"><h2>最近保存した判定</h2>{savedResults.map(record=><Link className="recent-result" key={record.id} href={`/?saved=${record.id}`}><span>{garmentRegistry[record.garmentType].label}</span><strong>{statusLabels[record.result.overall]}</strong><small>{record.updatedAt?.slice(0,10)}</small></Link>)}</section>}
    <GarmentChooser selected={garmentType} onChange={type=>{setGarmentType(type);setResult(null);setValues({})}}/>
    <div className="card stitch"><label className="field">あなたのぬい<select aria-label="あなたのぬい" value={selected} onChange={e=>selectProfile(e.target.value)}><option value="">{profiles.length?"選ぶ":"まだ登録されていません"}</option>{profiles.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{!profile&&<p className="small">{profiles.length?"登録したぬいを選ぶと、採寸した数字が入ります。":"先にあなたのぬいを登録すると、ここで選べるようになります。"}</p>}<h2>{garmentRegistry[garmentType].label}の寸法</h2><p className="field-note">服の寸法を、販売ページやタグを見ながら入力します。</p><div className="grid">{fields.map(field=><label className="field" key={field}><span>{garmentFieldLabels[field]}</span><input inputMode="decimal" placeholder="cm" value={values[field]??""} onChange={e=>setValues(current=>({...current,[field]:e.target.value}))}/>{circumference(field)&&<select aria-label={`${garmentFieldLabels[field]}の測り方`} value={modes[field]??"circumference"} onChange={e=>setModes(current=>({...current,[field]:e.target.value as "circumference"|"flat"}))}><option value="circumference">一周</option><option value="flat">平置き</option></select>}</label>)}</div><div className="inline-control"><label className="field">伸び<select value={stretch} onChange={e=>setStretch(e.target.value as Stretch)}>{Object.entries(stretchLabels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><button disabled={!canJudge} onClick={judge}>判定する</button></div>{!canJudge&&<p className="disabled-hint">判定するには、{missingFitFields.join("・")}を選択・入力してください。</p>}</div>
    {result&&<div className="card stitch"><div className="result-visual"><div className="result-chip"><small>総合</small><strong>{statusLabels[result.overall]}</strong></div><div className="result-chip"><small>ぴた度</small><strong>{result.overall==="unknown"?"—":result.score}</strong></div></div><p className="save-hint">判定は寸法から見た目安です。気になる部位を開いて確認できます。</p><div className="metric-grid">{result.parts.map((part:FitPart)=><div className="metric" key={part.field??part.name}><b>{part.name}</b><small>{statusLabels[part.status]}</small>{part.reasonCode&&<details><summary>?</summary><p className="small">{reasonLabels[part.reasonCode]??"採寸条件を確認してください"}</p></details>}</div>)}</div><p className="small">確度：{({high:"しっかり",medium:"まずまず",low:"ざっくり"} as const)[result.confidence]}</p><div className="actions"><button onClick={saveResult}>保存</button><ShareActions title="ぬい服フィット" status={statusLabels[result.overall]} url={`${location.origin}/s/${sharePayload}`}/><button className="secondary" onClick={()=>navigator.clipboard?.writeText(`${location.origin}/s/${sharePayload}`)}>リンクをコピー</button><a href={`/g/${garmentPayload}`}><button className="secondary">この服のサイズ確認リンクを作る</button></a></div><p className="small link-help">この服の寸法を、他の人が自分のぬいで確認できるリンクです。</p></div>}<Toast key={notice} message={notice}/><p className="small">判定は素材や形によって変わる、寸法から見た目安です。</p></>;
}
