"use client";
import Image from "next/image";
import Link from "next/link";
import {useEffect,useState} from "react";
import {ShareActions} from "@/components/share/ShareActions";
import {Toast} from "@/components/ui/Toast";
import {LoadingSkeleton} from "@/components/ui/LoadingSkeleton";
import {judgePouch,type Orientation} from "@/features/pouch/engine";
import {encodeShare} from "@/lib/share";
import {listProfiles,putRecord,storageUnavailable} from "@/lib/storage";
import type {Profile} from "@/features/profiles/types";

const labels={noFit:"入らないかも",snug:"ぴたっと",stable:"ちょうど",moves:"動きやすいかも"} as const;
function Diagram({result,side}:{result:ReturnType<typeof judgePouch>|null;side?:boolean}){const ratio=result?(side?result.depth/result.height:result.width/result.height):.7;const width=Math.min(160,Math.max(48,100*ratio));return <svg aria-label={side?"ポーチ側面図":"ポーチ正面図"} role="img" viewBox="0 0 180 150" width="180" height="150"><rect x={(180-width)/2} y="15" width={width} height="120" rx="12" fill="#fff9f4" stroke="#a95043" strokeWidth="3"/><rect x={(180-width)/2+8} y="35" width={Math.max(20,width-16)} height="85" rx="8" fill="#f8e1d9" stroke="#a95043" strokeDasharray="5 4"/><text x="90" y="145" textAnchor="middle" fontSize="11" fill="#493c38">{side?"奥行 × 高さ":"幅 × 高さ"}</text></svg>}

export default function Pouch(){
  const [profiles,setProfiles]=useState<Profile[]>([]);const [loading,setLoading]=useState(true);const [count,setCount]=useState(1);const [selected,setSelected]=useState<string[]>(["","",""]);const [inner,setInner]=useState({width:"",height:"",depth:""});const [orientation,setOrientation]=useState<Orientation>("auto");const [result,setResult]=useState<ReturnType<typeof judgePouch>|null>(null);const [notice,setNotice]=useState("");
  useEffect(()=>{const timer=window.setTimeout(()=>{if(storageUnavailable())setNotice("この端末では保存できません。今だけ使えます")},0);listProfiles().then(value=>{setProfiles(value);setLoading(false)}).catch(()=>{setLoading(false);setNotice("この端末では保存できません。今だけ使えます")});return()=>window.clearTimeout(timer)},[]);
  const chosen=selected.slice(0,count).map(id=>profiles.find(profile=>profile.id===id));const missing=chosen.some(profile=>!profile?.measurements.height||!profile.measurements.maxWidth||!profile.measurements.maxDepth)||!inner.width||!inner.height||!inner.depth;
  function judge(){if(missing){setNotice("入力内容を確認してください");return}const items=chosen.map(profile=>({height:profile!.measurements.height!,width:profile!.measurements.maxWidth!,depth:profile!.measurements.maxDepth!}));setResult(judgePouch(items,{width:Number(inner.width),height:Number(inner.height),depth:Number(inner.depth)},orientation));setNotice("")}
  async function save(){if(!result)return;await putRecord("pouchDrafts",{id:crypto.randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),dataVersion:1,selected,inner,orientation,result});setNotice("この端末に保存しました")}
  const share=encodeShare({kind:"pouch",name:chosen[0]?.name,count,overall:result?.status,orientation:result?.orientation,avatarTheme:chosen[0]?.avatarTheme});const orientationLabel=result?.orientation==="mixed"?"混在":result?.orientation==="upright"?"立てる":"横向き";
  return <><h1 className="sr-only">ぬいポーチ内寸シミュレーター</h1><section className="hero"><span className="pill">ポーチ</span><h2>ポーチに入るか見る</h2><p className="small">ぬいとポーチの内側を比べて、持ち歩けるか確認します。</p><Image className="pouch-hero-image" src="/pouch-explainer.jpg" alt="ぬいをポーチに入れて内寸を比べるイメージ" width={420} height={300} priority/></section>
    {loading&&<LoadingSkeleton label="登録したぬいを読み込み中"/>}
    <div className="card stitch"><label className="field">ぬいの数<select value={count} onChange={e=>{setCount(Number(e.target.value));setResult(null)}}>{[1,2,3].map(value=><option value={value} key={value}>{value}体</option>)}</select></label>{selected.slice(0,count).map((id,index)=><label className="field" key={index}>ぬい {index+1}<select value={id} onChange={e=>setSelected(current=>current.map((value,i)=>i===index?e.target.value:value))}><option value="">選ぶ</option>{profiles.map(profile=><option value={profile.id} key={profile.id}>{profile.name}</option>)}</select></label>)}<h2>ポーチの内寸</h2><p className="small">内側の使える空間を測ります。外側の寸法ではありません。</p><div className="grid">{[["width","内幅"],["height","内高"],["depth","内奥行"]].map(([key,label])=><label className="field" key={key}>{label}<input inputMode="decimal" placeholder="cm" value={inner[key as keyof typeof inner]} onChange={e=>setInner(current=>({...current,[key]:e.target.value}))}/></label>)}</div><div className="inline-control"><label className="field">向き<select value={orientation} onChange={e=>setOrientation(e.target.value as Orientation)}><option value="auto">自動</option><option value="upright">立てる</option><option value="sideways">横向き</option></select></label><button onClick={judge}>判定する</button></div></div>
    {!loading&&missing&&<div className="card missing-guide"><strong>判定の前に、3つ確認してください</strong><ol><li>上の選択欄から、入れたいぬいを選ぶ</li><li>「ぬいを登録」で全高・最大幅・最大奥行を登録する</li><li>ポーチの「内幅・内高・内奥行」を入力する</li></ol><p className="small">ぬいの採寸がまだなら、先に登録画面で追加できます。</p><Link href="/nui"><button type="button" className="secondary">ぬいの寸法を追加する</button></Link></div>}
    {result&&<div className="card stitch"><div className="result-visual"><div className="result-chip"><small>判定</small><strong>{labels[result.status]}</strong></div><div className="result-chip"><small>向き</small><strong>{orientationLabel}</strong></div></div><div className="grid"><Diagram result={result}/><Diagram result={result} side/></div><div className="metric-grid"><div className="metric"><b>{result.remaining[0].toFixed(1)}cm</b><small>幅の余白</small></div><div className="metric"><b>{result.remaining[1].toFixed(1)}cm</b><small>高さの余白</small></div><div className="metric"><b>{result.remaining[2].toFixed(1)}cm</b><small>奥行の余白</small></div></div>{result.spacer>0&&<p className="save-hint">左右に約{result.spacer.toFixed(1)}cmずつ空ける目安</p>}<div className="actions"><button onClick={save}>保存</button><ShareActions title="ぬいポーチ" status={labels[result.status]} url={`${location.origin}/s/${share}`}/><button className="secondary" onClick={()=>navigator.clipboard?.writeText(`${location.origin}/s/${share}`)}>リンクをコピー</button></div></div>}
    <Toast key={notice} message={notice}/></>;
}
