export type Status="blocked"|"tight"|"fit"|"roomy"|"unknown";
export type Stretch="none"|"low"|"medium"|"high";
const stretch:Record<Stretch,number>={none:1,low:1.03,medium:1.07,high:1.12};
const softness={firm:1,balanced:.96,soft:.91} as const;
export function classify(r:number,kind:"head"|"body"|"hat"):Status{const [a,b,c]=kind==="head"?[.94,1.02,1.15]:kind==="hat"?[.96,1.02,1.12]:[.97,1.03,1.2];return r<a?"blocked":r<b?"tight":r<=c?"fit":"roomy";}
export function fitRatio(garment:number,plush:number,mode:"circumference"|"flat",factor:number){return garment*(mode==="flat"?2:1)*factor/plush;}
export function fitScore(ratios:number[],status:Status){if(!ratios.length)return 0;const raw=ratios.reduce((s,r)=>s+Math.max(0,100-Math.abs(r-1.08)*180),0)/ratios.length;const rounded=Math.round(raw/5)*5;return Math.min(status==="blocked"?35:status==="tight"?60:100,Math.max(0,rounded));}
export type FitReasonCode="HEAD_OPENING_TOO_SMALL"|"HEAD_OPENING_TIGHT"|"HEAD_ROOMY"|"BODY_TIGHT"|"BODY_ROOMY"|"LENGTH_SHORT"|"LENGTH_LONG"|"MISSING_COMPARISON";
function reasonCode(name:string,status:Status,ratio:number):FitReasonCode{if(name==="頭")return status==="blocked"?"HEAD_OPENING_TOO_SMALL":status==="tight"?"HEAD_OPENING_TIGHT":status==="roomy"?"HEAD_ROOMY":"MISSING_COMPARISON";if(name==="胴")return status==="tight"||status==="blocked"?"BODY_TIGHT":status==="roomy"?"BODY_ROOMY":"MISSING_COMPARISON";return ratio<.82?"LENGTH_SHORT":ratio>1.15?"LENGTH_LONG":"MISSING_COMPARISON"}
export function judgeFit(input:{opening?:number;chest?:number;length?:number;plushHead?:number;plushBody?:number;plushLength?:number;stretch:Stretch;softness:"firm"|"balanced"|"soft"}){const parts:{name:string;status:Status;ratio:number;reasonCode:FitReasonCode}[]=[];if(input.opening&&input.plushHead){const ratio=fitRatio(input.opening,input.plushHead,"circumference",stretch[input.stretch]);const status=classify(ratio,"head");parts.push({name:"頭",ratio,status,reasonCode:reasonCode("頭",status,ratio)})}if(input.chest&&input.plushBody){const ratio=fitRatio(input.chest,input.plushBody,"circumference",stretch[input.stretch]);const status=classify(ratio,"body");parts.push({name:"胴",ratio,status,reasonCode:reasonCode("胴",status,ratio)})}if(input.length&&input.plushLength){const ratio=input.length/input.plushLength;const status=ratio<.82||ratio>1.15?"tight":"fit";parts.push({name:"丈",ratio,status,reasonCode:reasonCode("丈",status,ratio)})}const overall=parts.some(p=>p.status==="blocked")?"blocked":parts.some(p=>p.status==="tight")?"tight":parts.length<2?"unknown":parts.every(p=>p.status==="fit")?"fit":parts.filter(p=>p.status==="roomy").length>parts.length/2?"roomy":"fit";return {overall,parts,score:fitScore(parts.map(p=>p.ratio),overall),confidence:parts.length>=3?"high":parts.length>=2?"medium":"low"} as const;}
